
package View.GUI_MenuAdmin;

import View.GUI_AssignmentMobile.Menu_AssignmentMobie;
import View.GUI_Login.Login;
import View.GUI_Marcas.Menu_Marcas;
import View.GUI_Mobiles.Menu_Mobiles;

/**
 *
 * @author alexis
 */
public class MenuPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalAdmin
     */
    public MenuPrincipalAdmin() {
        initComponents();
        this.setTitle("Mobile Store UAM-C");
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresar_Login = new javax.swing.JButton();
        asignar_Mobiles = new javax.swing.JButton();
        control_Marcas = new javax.swing.JButton();
        control_Mobiles = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Regresar.png"))); // NOI18N
        regresar_Login.setText("Regresar a Login");
        regresar_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(regresar_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        asignar_Mobiles.setText("Asignación de Dispositivos Móviles a Marcas");
        asignar_Mobiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignar_MobilesActionPerformed(evt);
            }
        });
        jPanel1.add(asignar_Mobiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        control_Marcas.setText("Control de Marcas");
        control_Marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control_MarcasActionPerformed(evt);
            }
        });
        jPanel1.add(control_Marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        control_Mobiles.setText("Control de Dispositivos Móviles");
        control_Mobiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control_MobilesActionPerformed(evt);
            }
        });
        jPanel1.add(control_Mobiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel2.setText("Menú de opciones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home_wallpaper_0.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void control_MobilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_MobilesActionPerformed
        new Menu_Mobiles().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_control_MobilesActionPerformed

    private void control_MarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_MarcasActionPerformed
        new Menu_Marcas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_control_MarcasActionPerformed

    private void asignar_MobilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignar_MobilesActionPerformed
        new Menu_AssignmentMobie().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_asignar_MobilesActionPerformed

    private void regresar_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_LoginActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresar_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignar_Mobiles;
    private javax.swing.JButton control_Marcas;
    private javax.swing.JButton control_Mobiles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresar_Login;
    // End of variables declaration//GEN-END:variables
}
