
package View.GUI_MenuCliente;

import View.GUI_Consultas.*;
import View.GUI_Login.Login;

/**
 *
 * @author alexis
 */
public class MenuPrincipalCliente extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalCliente
     */
    public MenuPrincipalCliente() {
        initComponents();
        this.setTitle("Mobile Store UAM-C");
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresar_Login = new javax.swing.JButton();
        verMobilesMarca = new javax.swing.JButton();
        verMarcas = new javax.swing.JButton();
        verMobiles = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Regresar.png"))); // NOI18N
        regresar_Login.setText("Regresar a Login");
        regresar_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(regresar_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        verMobilesMarca.setText("Consulta de dispositivos móviles por marca");
        verMobilesMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMobilesMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(verMobilesMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        verMarcas.setText("Consulta de marcas registradas");
        verMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMarcasActionPerformed(evt);
            }
        });
        jPanel1.add(verMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        verMobiles.setText("Conslta de dispositivos móviles");
        verMobiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMobilesActionPerformed(evt);
            }
        });
        jPanel1.add(verMobiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel2.setText("Menú de opciones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home_wallpaper_0.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresar_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_LoginActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresar_LoginActionPerformed

    private void verMobilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMobilesActionPerformed
        new Consulta_Mobiles_Cliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_verMobilesActionPerformed

    private void verMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMarcasActionPerformed
        new Consultar_Marcas_Cliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_verMarcasActionPerformed

    private void verMobilesMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMobilesMarcaActionPerformed
        new Consulta_Mobile_Marca_Cliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_verMobilesMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresar_Login;
    private javax.swing.JButton verMarcas;
    private javax.swing.JButton verMobiles;
    private javax.swing.JButton verMobilesMarca;
    // End of variables declaration//GEN-END:variables
}
