
package View.GUI_AssignmentMobile;

import View.GUI_MenuAdmin.MenuPrincipalAdmin;

/**
 *
 * @author alexis
 */
public class Menu_AssignmentMobie extends javax.swing.JFrame {

    /**
     * Creates new form Menu_AssignmentMobie
     */
    public Menu_AssignmentMobie() {
        initComponents();
        this.setTitle("Asignación de Móviles a una Marca");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresar_MenuAdmin = new javax.swing.JButton();
        consulta_MobileMarca = new javax.swing.JButton();
        baja_MobileMarca = new javax.swing.JButton();
        alta_MobileMarca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar_MenuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Regresar.png"))); // NOI18N
        regresar_MenuAdmin.setText("Regresar a Menú Administrador");
        regresar_MenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_MenuAdminActionPerformed(evt);
            }
        });
        jPanel1.add(regresar_MenuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        consulta_MobileMarca.setText("Consultar Móviles en una Marca");
        consulta_MobileMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_MobileMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(consulta_MobileMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        baja_MobileMarca.setText("Baja de un Móvil en una Marca");
        baja_MobileMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baja_MobileMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(baja_MobileMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        alta_MobileMarca.setText("Alta de un Móvil en una Marca");
        alta_MobileMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alta_MobileMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(alta_MobileMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel2.setText("Menú Asignación de Dispositivos Móviles");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home_wallpaper_0.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alta_MobileMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alta_MobileMarcaActionPerformed
        new Alta_Mobile_Marca().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alta_MobileMarcaActionPerformed

    private void baja_MobileMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baja_MobileMarcaActionPerformed
        new Baja_Mobile_Marca().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_baja_MobileMarcaActionPerformed

    private void consulta_MobileMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_MobileMarcaActionPerformed
        new Consulta_Mobile_Marca().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consulta_MobileMarcaActionPerformed

    private void regresar_MenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_MenuAdminActionPerformed
        new MenuPrincipalAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresar_MenuAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_AssignmentMobie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_AssignmentMobie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_AssignmentMobie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_AssignmentMobie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_AssignmentMobie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alta_MobileMarca;
    private javax.swing.JButton baja_MobileMarca;
    private javax.swing.JButton consulta_MobileMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresar_MenuAdmin;
    // End of variables declaration//GEN-END:variables
}
