
package View.GUI_Mobiles;

import ConectionSQL.Mobile_DB;
import Model.Mobile;
import javax.swing.JOptionPane;

/**
 *
 * @author alexis
 */
public class Alta_Mobile extends javax.swing.JFrame {
    Mobile_DB mobile_db = new Mobile_DB();

    /**
     * Creates new form Alta_Mobile
     */
    public Alta_Mobile() {
        initComponents();
        this.setTitle("Control de Móviles");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        altaPrecio = new javax.swing.JTextField();
        altaColor = new javax.swing.JTextField();
        altaProcesador = new javax.swing.JTextField();
        altaNombre = new javax.swing.JTextField();
        regresar_MenuMobile = new javax.swing.JButton();
        altaMobile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(altaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, -1));
        jPanel1.add(altaColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 210, -1));
        jPanel1.add(altaProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 210, -1));
        jPanel1.add(altaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 210, -1));

        regresar_MenuMobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Regresar.png"))); // NOI18N
        regresar_MenuMobile.setText("Regresar a Menú Móviles");
        regresar_MenuMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_MenuMobileActionPerformed(evt);
            }
        });
        jPanel1.add(regresar_MenuMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        altaMobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        altaMobile.setText("Dar de Alta");
        altaMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaMobileActionPerformed(evt);
            }
        });
        jPanel1.add(altaMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        jLabel6.setText("Precio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel5.setText("Color:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel4.setText("Procesador:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel2.setText("Alta de dispositivo móvil");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home_wallpaper_0.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaMobileActionPerformed
        int claveMobile;
        if (!"".equals(altaNombre.getText()) && !"".equals(altaProcesador.getText()) &&
                 !"".equals(altaColor.getText()) && !"".equals(altaPrecio.getText())) {
            claveMobile = mobile_db.generaClaveMob();
            Mobile m = new Mobile();
            m.setClaveMobile(claveMobile);
            m.setNombre(altaNombre.getText());
            m.setProcesador(altaProcesador.getText());
            m.setColor(altaColor.getText());
            m.setPrecio(altaPrecio.getText());
            mobile_db.altaMobile(m);
            JOptionPane.showMessageDialog(null, "El dispositivo fue dado de alta con la clave: "+claveMobile,"",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Porfavor, ingresa toda la información","",JOptionPane.ERROR_MESSAGE);
        }
        altaNombre.setText("");
        altaProcesador.setText("");
        altaColor.setText("");
        altaPrecio.setText("");
    }//GEN-LAST:event_altaMobileActionPerformed

    private void regresar_MenuMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_MenuMobileActionPerformed
        new Menu_Mobiles().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresar_MenuMobileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta_Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta_Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta_Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta_Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta_Mobile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altaColor;
    private javax.swing.JButton altaMobile;
    private javax.swing.JTextField altaNombre;
    private javax.swing.JTextField altaPrecio;
    private javax.swing.JTextField altaProcesador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresar_MenuMobile;
    // End of variables declaration//GEN-END:variables
}
