
package View.GUI_Mobiles;

import View.GUI_MenuAdmin.MenuPrincipalAdmin;

/**
 *
 * @author alexis
 */
public class Menu_Mobiles extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Mobiles
     */
    public Menu_Mobiles() {
        initComponents();
        this.setTitle("Control de Móviles");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresar_MenuAdmin = new javax.swing.JButton();
        consulta_Mobile = new javax.swing.JButton();
        baja_Mobile = new javax.swing.JButton();
        alta_Mobile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar_MenuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Regresar.png"))); // NOI18N
        regresar_MenuAdmin.setText("Regresar a Menú Administrador");
        regresar_MenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_MenuAdminActionPerformed(evt);
            }
        });
        jPanel1.add(regresar_MenuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        consulta_Mobile.setText("Consulta de Dispositivos Móviles");
        consulta_Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_MobileActionPerformed(evt);
            }
        });
        jPanel1.add(consulta_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        baja_Mobile.setText("Baja de Dispositivos Móviles");
        baja_Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baja_MobileActionPerformed(evt);
            }
        });
        jPanel1.add(baja_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        alta_Mobile.setText("Alta de Dispositivos Móviles");
        alta_Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alta_MobileActionPerformed(evt);
            }
        });
        jPanel1.add(alta_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel2.setText("Menú Control de Dispositivos Móviles");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home_wallpaper_0.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alta_MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alta_MobileActionPerformed
        new Alta_Mobile().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alta_MobileActionPerformed

    private void baja_MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baja_MobileActionPerformed
        new Baja_Mobile().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_baja_MobileActionPerformed

    private void consulta_MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_MobileActionPerformed
        new Consulta_Mobiles().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consulta_MobileActionPerformed

    private void regresar_MenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_MenuAdminActionPerformed
        new MenuPrincipalAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresar_MenuAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Mobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Mobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Mobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Mobiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Mobiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alta_Mobile;
    private javax.swing.JButton baja_Mobile;
    private javax.swing.JButton consulta_Mobile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresar_MenuAdmin;
    // End of variables declaration//GEN-END:variables
}
