
package View.GUI_Marcas;

import View.GUI_MenuAdmin.MenuPrincipalAdmin;

/**
 *
 * @author alexis
 */
public class Menu_Marcas extends javax.swing.JFrame {

    /** Creates new form Menu_Marcas */
    public Menu_Marcas() {
        initComponents();
        this.setTitle("Control de Móviles");
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresar_MenuAdmin = new javax.swing.JButton();
        ver_Marcas = new javax.swing.JButton();
        baja_Marca = new javax.swing.JButton();
        alta_Marca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar_MenuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Regresar.png"))); // NOI18N
        regresar_MenuAdmin.setText("Regresar a Menú Administrador");
        regresar_MenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_MenuAdminActionPerformed(evt);
            }
        });
        jPanel1.add(regresar_MenuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        ver_Marcas.setText("Consulta de Marcas Registradas");
        ver_Marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_MarcasActionPerformed(evt);
            }
        });
        jPanel1.add(ver_Marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        baja_Marca.setText("Baja de Marcas Registradas");
        baja_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baja_MarcaActionPerformed(evt);
            }
        });
        jPanel1.add(baja_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        alta_Marca.setText("Alta de Marcas Registradas");
        alta_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alta_MarcaActionPerformed(evt);
            }
        });
        jPanel1.add(alta_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel2.setText("Menú Control de Marcas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home_wallpaper_0.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresar_MenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_MenuAdminActionPerformed
        new MenuPrincipalAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresar_MenuAdminActionPerformed

    private void alta_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alta_MarcaActionPerformed
        new Alta_Marca().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_alta_MarcaActionPerformed

    private void baja_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baja_MarcaActionPerformed
        new Baja_Marca().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_baja_MarcaActionPerformed

    private void ver_MarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_MarcasActionPerformed
        new Consultar_Marcas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ver_MarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Marcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alta_Marca;
    private javax.swing.JButton baja_Marca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresar_MenuAdmin;
    private javax.swing.JButton ver_Marcas;
    // End of variables declaration//GEN-END:variables

}
