
package View.GUI_Consultas;

import ConectionSQL.Marcas_DB;
import Model.Marca;
import View.GUI_MenuCliente.MenuPrincipalCliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexis
 */
public class Consultar_Marcas_Cliente extends javax.swing.JFrame {
    Marcas_DB marca_db = new Marcas_DB();

    /**
     * Creates new form Consultar_Marcas
     */
    public Consultar_Marcas_Cliente() {
        initComponents();
        this.setTitle("Control de Marcas");
        this.setLocationRelativeTo(null);
    }
    
    public void listarDatos() { // Con esta función se muestra la tabla
        ArrayList<Marca> marcas;
        marcas = marca_db.consultarMarcas();
        DefaultTableModel tb = (DefaultTableModel)tablaMarcas.getModel();
        for(Marca m: marcas) {
            tb.addRow(new Object[]{m.getClaveMarca(),m.getNombre(),m.getSitioWeb()});
        }
    }
    
    public void limpiarFormulario() {   // Con esta función se limpia la tabla
        DefaultTableModel tb = (DefaultTableModel)tablaMarcas.getModel();
        for (int i=tb.getRowCount()-1; i>=0; i--)
            tb.removeRow(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresaMenuMarcas = new javax.swing.JButton();
        verMarcas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMarcas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresaMenuMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Regresar.png"))); // NOI18N
        regresaMenuMarcas.setText("Regresar a Menú Marcas");
        regresaMenuMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresaMenuMarcasActionPerformed(evt);
            }
        });
        jPanel1.add(regresaMenuMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        verMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Lupa.png"))); // NOI18N
        verMarcas.setText("Consulta de Marcas");
        verMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMarcasActionPerformed(evt);
            }
        });
        jPanel1.add(verMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        tablaMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Clave Marca", "Nombre", "Sitio Web"
            }
        ));
        jScrollPane1.setViewportView(tablaMarcas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 590, 160));

        jLabel2.setText("Consulta de marcas registradas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home_wallpaper_0.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresaMenuMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaMenuMarcasActionPerformed
        new MenuPrincipalCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresaMenuMarcasActionPerformed

    private void verMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMarcasActionPerformed
        limpiarFormulario();
        listarDatos();
    }//GEN-LAST:event_verMarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_Marcas_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_Marcas_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_Marcas_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_Marcas_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_Marcas_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresaMenuMarcas;
    private javax.swing.JTable tablaMarcas;
    private javax.swing.JButton verMarcas;
    // End of variables declaration//GEN-END:variables
}
